### ISSUE TITLE
SetupScript mysql4-upgrade-2.1.1-2.2.0.php läut nicht

### ISSUE THREAD

**Issue by riconeitzel** [firegento/firegento-magesetup#199] opened 2015-09-29 14:33 UTC
Ursache bisher unbekannt, sollte aber gefixt werden. See #135

**Comment by riconeitzel** [comment] 2015-09-29 14:55
See #174

**Comment by riconeitzel** [comment] 2015-09-29 14:57
See #171

**Comment by riconeitzel** [comment] 2015-10-06 12:43
Intermediate fix: You can disable the caches in magento, reset the core_resource entry for "firegento_magesetup" to 2.1.1 and reload the frontend.

**Comment by Schrank** [comment] 2015-11-03 11:31
Can you reproduce the problem? I can't. How to?

**Comment by riconeitzel** [comment] 2015-11-03 12:43
I have also no idea. I have only this issue created, there with we him not out the eyes lose.

**Comment by sprankhub** [comment] 2015-11-03 17:16
If it is not reproducable and nobody has an idea, we should close this.

**Comment by riconeitzel** [comment] 2015-11-03 17:17
¯\_(⊙︿⊙)_/¯ but there are people, having that issue … :-/ @therouv any thoughts?

**Comment by sprankhub** [comment] 2015-11-03 17:19
[shameless self advertising] Yeah, probably people which do not have a proper [deployment process](http://www.coderblog.de/deployment-for-small-and-medium-sized-magento-shops/)[/shameless self advertising]

**Comment by sprankhub** [comment] 2015-11-04 08:20
To elaborate a bit more: People update e.g. by uploading single files. The `config.xml` is uploaded, page is opened, `core_resource` table is updated. Afterwards, the upgrade script is uploaded. It will not be executed any more, because the `core_resource` entry is already updated. This is nothing we can solve on our side.

**Comment by schneemannski** [comment] 2015-12-01 16:05
Rico Neitzel wrote:

Intermediate fix: You can disable the caches in magento, reset the core_resource entry for "firegento_magesetup" to 2.1.1 and reload the frontend.

How do i reset the core_resource entry exactly?

I would also pay directly for fixing my installation of firegento-magesetup. So if any Pro of you has got a little bit of time to invest, i would be appreciated...

**Comment by sprankhub** [comment] 2015-12-01 17:24
@schneemannski have a look at the database table `core_resource`. Search for the code `magesetup_setup`. Change the `version` and `data_version` to `2.1.1`.

**Comment by sprankhub** [comment] 2015-12-13 12:57
I am quite sure that the issue is caused by an [unclean upgrade](https://github.com/firegento/firegento-magesetup/issues/199#issuecomment-153631394), so that I close this issue. If someone proves that it is caused by something else, open a new issue or reopen this one.

**Closed by sprankhub** 2015-12-13 12:57 UTC
Labels: bug

**Comment by UZi02** [comment] 2015-12-23 09:19
I installed everything via Magento Connect Manager. I also get the message "Ungültiger Attributtyp". So what did I wrong? Just Paypal as payment method is working.

**Comment by Schrank** [comment] 2015-12-23 09:21
Did you try the recommendation?
Intermediate fix: You can disable the caches in magento, reset the core_resource entry for "firegento_magesetup" to 2.1.1 and reload the frontend.

**Comment by UZi02** [comment] 2015-12-23 14:44
I didn't. I think, when a topic is closed, it's solved and working out of the box. :)
Will try now and tell you later.

**Comment by UZi02** [comment] 2015-12-23 14:57
Yes, this fix works.
I just wanted to say that I don't think that I made an unclean upgrade (it's a fresh installation and the plugins were all loaded via Magento Connect) as mentioned by sprankhub.
